github:andrea-mariadb-2, andrea_mariadb, andipandy111, 777ninjamusic
patreon: andrea_mariadb
open_collective: andrea_mariadb
ko_fi: # Replace with a single Ko-fi username
tidelift: npm, babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: andrea-mariadb
issuehunt: andrea-mariadb
otechie: andrea-mariadb
custom: 'https://www.youtube.com/channel/UCuoDzKdqTwXtJe5kwo4tNYQ', 'https://www.youtube.com/channel/UCeTsecOxtD8zuDKPpcL9crg', https://www.youtube.com/channel/UCzTBP3CKnn_Pfn9x1ESaOZA, https://www.youtube.com/channel/UCC28NtoyhL4o_tg3r1cmicA
.npm
.yml
.yaml

